# Ansible documentation: "Handlers are executed in the order they are defined
# in the handlers section, not in the order listed in the notify statement."

- listen: Change ownership of rw mounts
  ansible.builtin.command:
    argv:
      - unshare
      - --user
      - --map-auto
      - --map-root-user
      - /bin/sh
      - -c
      - |
        chown --recursive {{ _rw_mount_uid }}:{{ _rw_mount_uid }} {{ item.path }}
  vars:
    _rw_mount_uid: "{{ item.idmap | int - idmap_start + 1 }}"
  loop: "{{ idmap_mounts_chown }}"
  async: 180
  poll: 0
  register: chown_rw_mounts

- listen: Block waiting on cloud-init to complete
  ansible.builtin.command:
    argv:
      - "lxc-{{ rootless | ansible.builtin.ternary('unpriv-', '') }}attach"
      - --lxcpath
      - "{{ lxc_path }}"
      - "{{ item }}"
      - --
      - /bin/sh
      - -c
      - cloud-init status --wait
  register: cloud_init_status
  failed_when: "'status: error' in cloud_init_status.stdout"
  ignore_errors: true
  loop: "{{ cloud_init_containers }}"

- listen: Block waiting on cloud-init to complete
  name: Save console log to local system
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/"
    flat: true
  loop: "{{ console_logs }}"

- listen: Change ownership of rw mounts
  name: Wait for mount permissions to be set
  ansible.builtin.async_status:
    jid: "{{ item }}"
  register: chown_rw_mounts_res
  until: chown_rw_mounts_res is finished
  retries: 5
  delay: 15
  loop: "{{ chown_rw_mounts.results | map(attribute='ansible_job_id') | list }}"

- name: Get all restartable instances
  ansible.builtin.command:
    cmd: "lxc-ls --lxcpath {{ lxc_path }} --running --groups cloud-init-boot --line"
  register: provisioned_containers_cmd
  changed_when: false
  listen: "Restart temporary config instances"

- name: Stop updated instances
  ansible.builtin.command:
    cmd: "lxc-autostart --lxcpath {{ lxc_path }} --shutdown --ignore-auto --groups cloud-init-boot"
  listen: "Restart temporary config instances"

- name: Start updated instances
  ansible.builtin.command:
    argv:
      - "lxc-{{ rootless | ansible.builtin.ternary('unpriv-', '') }}start"
      - --lxcpath
      - "{{ lxc_path }}"
      - "{{ item }}"
  loop: "{{ provisioned_containers_cmd.stdout_lines }}"
  listen: "Restart temporary config instances"
